//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTUDQL2_QUAN_LY_CCVIDEO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CapDoTaiKhoan
    {
        public CapDoTaiKhoan()
        {
            this.TaiKhoans = new HashSet<TaiKhoan>();
            this.Videos = new HashSet<Video>();
        }
    
        public int MaCapDo { get; set; }
        public string TenCapDo { get; set; }
        public Nullable<int> GiaTienDuyTri { get; set; }
    
        public virtual ICollection<TaiKhoan> TaiKhoans { get; set; }
        public virtual ICollection<Video> Videos { get; set; }
    }
}
