//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTUDQL2_QUAN_LY_CCVIDEO
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiVideo
    {
        public LoaiVideo()
        {
            this.Videos = new HashSet<Video>();
        }
    
        public int MaLoaiVideo { get; set; }
        public string TenLoaiVideo { get; set; }
    
        public virtual ICollection<Video> Videos { get; set; }
    }
}
