//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTUDQL2_QUAN_LY_CCVIDEO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayList
    {
        public int IDProfile { get; set; }
        public string TenPlayList { get; set; }
        public int IDVideo { get; set; }
        public int IDPlayList { get; set; }
    
        public virtual Profile Profile { get; set; }
        public virtual Video Video { get; set; }
    }
}
