//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTUDQL2_QUAN_LY_CCVIDEO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        public Video()
        {
            this.PlayLists = new HashSet<PlayList>();
            this.YeuThich_XemGanDay = new HashSet<YeuThich_XemGanDay>();
        }
    
        public int MaVideo { get; set; }
        public string TenVideo { get; set; }
        public string LinkVideo { get; set; }
        public Nullable<int> MaLoai_Video { get; set; }
        public string LinkImage { get; set; }
        public string LinkTrailer { get; set; }
        public Nullable<int> CapDoVideo { get; set; }
        public int Like { get; set; }
        public int Dislike { get; set; }
        public Nullable<System.DateTime> NgaySanXuat { get; set; }
        public Nullable<System.DateTime> NgayUpload { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> LuotXem { get; set; }
    
        public virtual CapDoTaiKhoan CapDoTaiKhoan { get; set; }
        public virtual LoaiVideo LoaiVideo { get; set; }
        public virtual ICollection<PlayList> PlayLists { get; set; }
        public virtual ICollection<YeuThich_XemGanDay> YeuThich_XemGanDay { get; set; }
    }
}
