//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTUDQL2_QUAN_LY_CCVIDEO
{
    using System;
    using System.Collections.Generic;
    
    public partial class YeuThich_XemGanDay
    {
        public int MaProfile { get; set; }
        public int MaVideo { get; set; }
        public int LoaiLuuTru { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
    
        public virtual Profile Profile { get; set; }
        public virtual Video Video { get; set; }
    }
}
